export const templates = {
    default: {
        name: "Default",
        previewStyles: { bgColor: "#F3F4F6", linkColor: "#FFFFFF", buttonColor: "#121B00" },
        styles: {
            template: "default",
            bgColor: "#F3F4F6",
            textColor: "#121B00",
            blockBgColor: "#FFFFFF",
            linkColor: "#FFFFFF",
            linkTextColor: "#121B00",
            actionButtonColor: "#121B00",
            actionButtonTextColor: "#FFFFFF",
            buttonShadowColor: "#000000",
            backgroundImageUrl: "",
        },
    },
    dark: {
        name: "Dark",
        previewStyles: { bgColor: "#121B00", linkColor: "#2a3b10", buttonColor: "#FFFFFF" },
        styles: {
            template: "dark",
            bgColor: "#121B00",
            textColor: "#FFFFFF",
            blockBgColor: "#2a3b10",
            linkColor: "#2a3b10",
            linkTextColor: "#FFFFFF",
            actionButtonColor: "#FFFFFF",
            actionButtonTextColor: "#121B00",
            buttonShadowColor: "#000000",
            backgroundImageUrl: "",
        },
    },
    shadow: {
        name: "Shadow",
        previewStyles: { bgColor: "#FDF5E6", linkColor: "#D946EF", buttonColor: "#D946EF" },
        styles: {
            template: "shadow",
            bgColor: "#FDF5E6",
            textColor: "#121B00",
            blockBgColor: "transparent",
            linkColor: "#D946EF",
            linkTextColor: "#FFFFFF",
            actionButtonColor: "#D946EF",
            actionButtonTextColor: "#FFFFFF",
            buttonShadowColor: "#121B00",
            backgroundImageUrl: "",
        },
    },
    image_bg: {
        name: "Image",
        previewStyles: { bgColor: "#cccccc", linkColor: "rgba(255, 255, 255, 0.8)", buttonColor: "#121B00" },
        styles: {
            template: "image_bg",
            bgColor: "#FFFFFF",
            textColor: "#FFFFFF",
            blockBgColor: "rgba(0, 0, 0, 0.2)",
            linkColor: "rgba(255, 255, 255, 0.8)",
            linkTextColor: "#121B00",
            actionButtonColor: "#121B00",
            actionButtonTextColor: "#FFFFFF",
            buttonShadowColor: "rgba(0, 0, 0, 0.4)",
            backgroundImageUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?q=80&w=2070",
        },
    },
};
